export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCEED = 'FETCH_MESSAGES_SUCCEED';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const FETCH_MORE_MESSAGES_SUCCEED = 'FETCH_MORE_MESSAGES_SUCCEED';

export const POST_MESSAGE_START = 'POST_MESSAGE_START';
export const POST_MESSAGE_SUCCEED = 'POST_MESSAGE_SUCCEED';
export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';
